---
tomcat_version: "9.0.85"
tomcat_user: tomcat
tomcat_group: tomcat
tomcat_install_dir: /opt/tomcat

tomcat_download_url: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"