#SPDX-License-Identifier: MIT-0
---
# tasks file for sample_role
- name: install apache2
    package:
      name: "{{pkg}}"
      state: latest
    when: ansible_facts['os_family'] == "Debian"
  
  - name: deployment
    copy: 
      src: index.html
      dest: /var/www/html/index.html
    notify:              #call handler file
     - start apache2