services:
  webserver:              # service ca nav deyc kay aahe te
    image: tejaskevate/docker-repo:website       # docker hub madhil save image ca path deyca
    ports:
      - 80:80
    volumes:
      - /opt/data:/var/www/html           # apache mounting path
  
  
  tomserver:
    image: ........          # tomcat image path from dockerhub
    ports:
      - 8080:8080
    environment:
      - department: "devops"

  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin123


# file run command
# docker compose up -d




