- name: install apache2
  hosts: all
  become: true                            # it is use for sudo command
  tasks:
    - name: install httpd if os is readhat
      yum:
       name: httpd
       state: latest
      when: ansible_os_family == "RedHat"
      ignore_errors: true                         #if error ignore perticular task
    - name: install apache2 if os is debian
      apt:
       name: apache2
       state: latest
      when: ansible_os_family == "RedHat"
   