- name: install multiple things
  hosts: all
  tasks:
    - name: print items
      debug:
        msg: "{{item}}"
      loop:
        - apple
        - mango
        - orange
        - banana
    - name: install vim, wget, httpd
      package: 
       name: "{{item}}"
       state: latest
      when: ansible_os_family == "Debian"
      loop:
        - vim
        - httpd
        - wget
        