---
- name: Install and Configure Tomcat (Any OS)
  hosts: all
  become: yes

  roles:
    - tomcat

    # ansible-playbook -i hosts tomcat.yaml            # run a ansible-playbook

    # http://<server-ip>:8080          # host machine ip